name: sing-box srs files
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

          echo "GEOIP_URL=https://github.com/Loyalsoldier/v2ray-rules-dat/raw/refs/heads/release/geoip.dat" >> $GITHUB_ENV
          echo "GEOSITE_URL=https://github.com/Loyalsoldier/v2ray-rules-dat/raw/refs/heads/release/geosite.dat" >> $GITHUB_ENV
        shell: bash

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/geodat2srs
          path: geodat2srs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geodat2srs/go.mod

      - name: Collect files
        run: |
          mkdir -p ./publish
          curl -sSL $GEOIP_URL > ./publish/geoip.dat
          curl -sSL $GEOIP_URL.sha256sum > ./publish/geoip.dat.sha256sum

          curl -sSL $GEOSITE_URL > ./publish/geosite.dat
          curl -sSL $GEOSITE_URL.sha256sum > ./publish/geosite.dat.sha256sum

      - name: Generate sing-box srs
        run: |
          go build -C geodat2srs ./
          ./geodat2srs/geodat2srs geoip -i ./publish/geoip.dat -o ./tmp/sing-box/rule-set-geoip/
          ./geodat2srs/geodat2srs geosite -i ./publish/geosite.dat -o ./tmp/sing-box/rule-set-geosite/

      - name: Move generated files to publish directory
        run: |
          mv ./publish /tmp/publish
          mv ./tmp/sing-box /tmp/publish/sing-box

      - name: Checkout release branch
        run: |
          git fetch origin release
          git checkout -B release origin/release

      - name: Git push assets to "release" branch
        run: |
          cp -r /tmp/publish/* .
          rm -rf /tmp/publish
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sing-box/ geoip.dat* geosite.dat*
          git commit -m "Update sing-box srs files on ${{ env.RELEASE_NAME }}" || echo "No changes to commit"
          git push origin release
